# code: language=ansible
---
- name: Install repository dependency packages
  ansible.builtin.apt:
    name:
      - python3-apt
      - python3-debian
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
# - name: Create GPG key directory
#   ansible.builtin.file:
#     path: "{{ etcd_apt_key_dest | dirname }}"
#     state: directory
#     mode: "0755"
# - name: Download GPG key
#   ansible.builtin.get_url:
#     url: "{{ etcd_apt_key_url }}"
#     dest: "{{ etcd_apt_key_download_dest }}"
#     mode: "0644"
#   register: gpg_key_download_result
# - name: Convert GPG key
#   ansible.builtin.command:
#     cmd: gpg --dearmor -o {{ etcd_apt_key_dest }} {{ etcd_apt_key_download_dest }}
#   when: gpg_key_download_result is changed
# - name: Add etcd repository
#   ansible.builtin.deb822_repository:
#     name: etcd
#     uris: https://packages.repository.com/debian
#     suites: "{{ ansible_facts.distribution_release }}"
#     components: main
#     signed_by: "{{ etcd_apt_key_dest }}"
#     enabled: true
#     state: present
#   register: apt_repository_result
# - name: Update apt cache
#   ansible.builtin.apt:
#     update_cache: true
#   when: apt_repository_result is changed
