# code: language=ansible
---
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /lib/systemd/system/etcd.service
    mode: "0644"
  notify: restart etcd
- name: Service etcd is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: etcd
    state: started
    enabled: true
# - name: allow etcd port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
